root: true
extends: standard
env:
  browser: true
  es6: true
  node: true
globals:
  global: false
  Drupal: false
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
rules:
  allow-parens: 0
  generator-star-spacing: 0
  no-multi-spaces:
    - error
    - {ignoreEOLComments: true}
  no-debugger: 0
  require-jsdoc: error
  valid-jsdoc:
    - error
    - {requireReturn: false}
